apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: nifi
spec:
  ports:
  - name: nifi1-https
    port: 8443
    protocol: TCP
    targetPort: nifi1-https
  selector:
    app: nifi
status:
  loadBalancer: {}
