apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: nifi
  name: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  strategy: {}
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - image: apache/nifi:1.19.0
        imagePullPolicy: IfNotPresent
        name: nifi1
        env: 
        - name: TZ
          value: Europe/Istanbul
        - name: NIFI_JVM_HEAP_INIT
          value: 4096m
        - name: NIFI_JVM_HEAP_MAX
          value: 4096m
        ports:
        - containerPort: 8443
          name: nifi-https
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 3Gi
        volumeMounts:
        - mountPath: /opt/nifi/nifi-current/conf
          name: nifi-data
          subPath: nifi1-conf
      restartPolicy: Always
      volumes:
      - name: nifi-data 
        persistentVolumeClaim:
            claimName: nifi-data-claim
status: {}
