apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - name: n8n-main
        image: n8nio/n8n:0.227.0
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "1"
            memory: "4Gi"
        env:
          - name: GENERIC_TIMEZONE
            value: Europe/Istanbul
          - name: EXECUTIONS_PROCESS
            value: main
          - name: NODE_OPTIONS
            value: --max-old-space-size=4096
        ports:
        - containerPort: 5678
