apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:3.4
#        resources:
#          requests:
#            cpu: "1"
#            memory: "2Gi"
#          limits:
#            cpu: "1"
#            memory: "4Gi"
        env:
          - name: ALLOW_PLAINTEXT_LISTENER
            value: yes
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: PLAINTEXT://172.17.0.2:9092
          - name: TZ
            value: "Europe/Istanbul"
#        ports:
#        - containerPort: 5678

