apiVersion: v1
kind: Service
metadata:
  name: n8n-service
spec:
  selector:
    app: n8n
  ports:
  - name: http
    port: 80
    targetPort: 5678
    nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - name: http
    port: 6379
    targetPort: 6379
    nodePort: 30081
  type: NodePort
