apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:8.7.1
        env:
          - name: XPACK_SECURITY_ENABLED
            value: "false"
          - name: ELASTICSEARCH_URL
            value: http://192.168.49.2:30083
          - name: ELASTICSEARCH_HOSTS
            value: http://192.168.49.2:30083
        ports:
        - containerPort: 5601
#        volumeMounts:
#        - name: config-volume
#          mountPath: /usr/share/kibana/config/kibana.yml
#          subPath: kibana.yml
#      volumes:
#      - name: config-volume
#        configMap:
#          name: kibana-config
