apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config
data:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false
    network.host: 0.0.0.0
