apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: default
spec:
  selector:
    app: kafka
  ports:
  - name: http
    port: 80
    targetPort: 9092
    nodePort: 30089
  type: NodePort

