apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.3.0
#        resources:
#          requests:
#            cpu: "1"
#            memory: "2Gi"
#          limits:
#            cpu: "1"
#            memory: "4Gi"
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: 192.168.49.2:30088
          - name: KAFKA_ADVERTISED_LISTENERS
#            value: PLAINTEXT://192.168.49.2:30089
#            value: PLAINTEXT://localhost:9092
            value: PLAINTEXT://192.168.49.2:30089,INTERNAL://localhost:9092
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: TZ
            value: "Europe/Istanbul"
#        ports:
#        - containerPort: 5678

