apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: default
spec:
  selector:
    app: zookeeper
  ports:
  - name: http
    port: 80
    targetPort: 2181
    nodePort: 30088
  type: NodePort

